### ISSUE TITLE
Create Initial Color Palette

### ISSUE THREAD

**Issue by walshb421** [walshb421/chess#23]
-**light and dark piece colors**
-dark mode/light mode
Style guide for:
-basic board colors
-headings/type
-background
-additional components around the board

**Comment by walshb421** [comment]
https://github.com/walshb421/chess/blob/main/src/assets/base.css

**Comment by Bryonnab** [comment]
Light team accent #97C497, 
Light team default piece color #D9D7D3, 
Dark team default piece color #504B43,
Dark team accent #60A561

**Comment by walshb421** [comment]
To get the font family working:
```css
@import url('https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap');

h1 {
  font-family: "Rubik", sans-serif;
  font-optical-sizing: auto;
  font-weight: 900;
  font-style: normal;
}

```
